server {
    listen 8080;
    server_name jz.dets.top;

    # 告诉 Nginx 实际访问者是 https，避免重定向时降级为 http://:8080
    location / {
        proxy_pass http://app:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }

    location /db-admin {
        auth_basic "DB Admin";
        auth_basic_user_file /etc/nginx/.htpasswd;

        # 把 /db-admin 重写为 / 传给后端
        rewrite ^/db-admin/?(.*)$ /$1 break;
        proxy_pass http://db-admin:8081;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto https;
    }
}
